import type { BpEvent, Member } from './types'

export const EVENTS: BpEvent[] = [
  { id:1, title:'Hack for Impact',            date:'November 1st, 2026', time:'TBD', loc:'TBD', type:'flagship', desc:'Our first annual hackathon. Student teams build real tech solutions for Durham Region nonprofits. Open to every program at OTU.', cap:100, status:'upcoming'    },
  { id:2, title:'Tech for Good Panel',        date:'Nov 2026',           time:'TBD', loc:'TBD', type:'panel',    desc:'90 minutes with OTU professors, Durham nonprofit leaders, and people working in social impact tech. Open to the whole campus.', cap:80,  status:'placeholder' },
  { id:3, title:'Learn Lab Series',           date:'Oct 2026',           time:'TBD', loc:'TBD', type:'lab',      desc:'Monthly skill sessions covering React, Figma, Git, agile, and client communication. Hands-on and beginner friendly.',           cap:40,  status:'placeholder' },
  { id:4, title:'Fall Info Session',          date:'Sept 2026',          time:'TBD', loc:'TBD', type:'social',   desc:'Learn what Blueprint is, meet the team, and find out how to apply. Food provided. Come as you are.',                           cap:60,  status:'upcoming'    },
  { id:5, title:'NPO Showcase Night',         date:'Apr 2027',           time:'TBD', loc:'TBD', type:'flagship', desc:'End of year demo night. Each team presents their delivered software to nonprofit clients, sponsors, faculty, and campus.',     cap:120, status:'placeholder' },
  { id:6, title:'Coffee Chats with Industry', date:'Monthly',            time:'TBD', loc:'TBD', type:'social',   desc:'Monthly 60-minute session with one industry professional. 15 Blueprint members. No slides, just real talk.',                   cap:15,  status:'placeholder' },
]

export const TEAM: Member[] = [
  { id:1, name:'Jun Bin Cheng',   role:'Founder',           program:'Ontario Tech University', year:'', initials:'J', isExec:true },
  { id:2, name:'Valerie Ekeigwe', role:'President',         program:'Ontario Tech University', year:'', initials:'V', isExec:true },
  { id:3, name:'Kumayl Zafar',    role:'Vice President',    program:'Ontario Tech University', year:'', initials:'K', isExec:true },
  { id:4, name:'Ngozika Nwachukwu', role:'VP of Tech & Web', program:'Ontario Tech University', year:'', initials:'N', isExec:true },
]

export const TEAMS = [
  {
    id: 'creative',
    name: 'Creative & Media Team',
    type: 'Creative',
    tagline: "Shape Blueprint OTU's brand, content, and storytelling across social media, events, recruitment, and digital platforms.",
    experience: 'Beginner-Friendly to Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['Social media strategy','Instagram','LinkedIn','Content planning','Canva','Figma','Photography','Video editing','Branding','Graphic design','Copywriting'],
    what: "Shape Blueprint OTU's brand, content, and storytelling across social media, events, recruitment, and digital platforms.",
    roles: [
      {
        title: 'Social Media Director',
        experience: 'Experience Preferred',
        description: "Leads Blueprint OTU's online presence across Instagram, LinkedIn, and other platforms. This role owns the content calendar, campaign direction, posting schedule, and overall social media voice.",
        responsibilities: [
          'Plan and manage the weekly/monthly content calendar',
          'Lead Instagram and LinkedIn content strategy',
          'Coordinate recruitment campaigns, event promotions, and announcements',
          'Write or review captions, post copy, and story content',
          'Track engagement, follower growth, and campaign performance',
          'Work with designers, photographers, and content creators to produce posts',
          "Make sure Blueprint OTU's online presence feels consistent and professional",
        ],
        requirements: [
          'Experience managing or helping run a social media page, club page, brand page, or personal content account',
          'Strong understanding of Instagram content, captions, stories, reels, and post timing',
          'Good writing and communication skills',
          'Organized enough to manage deadlines and posting schedules',
          'Able to understand the Blueprint OTU brand and keep content consistent',
          'Comfortable giving direction to content creators/designers',
        ],
        niceToHave: [
          'Canva, Figma, CapCut, or Adobe experience',
          'Experience with analytics/insights',
          'Experience growing a page or running campaigns',
        ],
      },
      {
        title: 'Content Creator',
        experience: 'Beginner-Friendly to Experience Preferred',
        description: 'Creates short-form content, captions, reels, stories, and behind-the-scenes content that makes Blueprint OTU feel active, human, and engaging.',
        responsibilities: [
          'Create Instagram reels, stories, and short-form videos',
          'Capture behind-the-scenes moments at meetings and events',
          'Help write captions and content ideas',
          'Support recruitment campaigns and event promotions',
          'Turn club updates into engaging student-friendly content',
          'Work with the Social Media Director to follow the content calendar',
        ],
        requirements: [
          'Experience creating content for Instagram, TikTok, YouTube Shorts, clubs, events, or personal projects',
          'Comfortable filming, editing, or planning content',
          'Good sense of what feels engaging to students',
          'Able to follow brand direction and deadlines',
          'Strong communication and creativity',
          'Comfortable being at events or working with people to capture content',
        ],
        niceToHave: [
          'CapCut, Canva, Adobe, or phone video editing experience',
          'Basic photography/videography skills',
          'Experience writing captions or hooks',
        ],
      },
      {
        title: 'Photographer / Videographer',
        experience: 'Experience Preferred',
        description: 'Captures high-quality photos and videos for Blueprint OTU events, campaigns, recruitment, and brand storytelling.',
        responsibilities: [
          'Take photos and videos at events, workshops, meetings, and campaigns',
          'Capture clean, professional-looking content for Instagram and LinkedIn',
          'Edit photos/videos when needed',
          'Organize media files for the team',
          'Work with the Creative & Media team to plan shoots',
          'Help create visual content that makes the chapter look active and credible',
        ],
        requirements: [
          'Experience taking photos or videos for events, clubs, personal projects, or clients',
          'Comfortable using a camera or phone camera well',
          'Basic understanding of lighting, framing, and composition',
          'Able to deliver content on time after events',
          'Organized with file storage and sharing',
          'Comfortable attending events to capture content',
        ],
        niceToHave: [
          'DSLR/mirrorless camera access',
          'Lightroom, Photoshop, Premiere Pro, CapCut, or DaVinci Resolve experience',
          'Experience shooting event recaps or social media reels',
        ],
      },
      {
        title: 'Director of Design',
        experience: 'Experience Required',
        description: 'Owns the visual identity of Blueprint OTU and makes sure all graphics, posters, templates, slide decks, and digital assets look consistent and polished.',
        responsibilities: [
          'Lead the design direction for social posts, posters, slide decks, and event graphics',
          'Create and maintain reusable design templates',
          "Make sure Blueprint OTU's branding is consistent across platforms",
          'Support website visuals, recruitment graphics, and campaign assets',
          'Work with the Social Media Director and Content Creator on campaigns',
          'Review designs before they are posted or published',
        ],
        requirements: [
          'Strong experience with graphic design, branding, or visual design',
          'Comfortable using Figma, Canva, Adobe Illustrator, Photoshop, or similar tools',
          'Good understanding of layout, typography, colour, spacing, and hierarchy',
          'Able to create clean, professional graphics without needing heavy direction',
          'Strong attention to detail',
          'Able to meet deadlines for campaigns and events',
        ],
        niceToHave: [
          'Experience creating brand systems or design templates',
          'Motion design or illustration experience',
          'Portfolio, Instagram design page, or sample graphics',
        ],
      },
    ],
  },
  {
    id: 'community',
    name: 'Community & Outreach Team',
    type: 'Outreach',
    tagline: "Grow Blueprint OTU's campus presence, member experience, recruitment pipeline, and external relationships.",
    experience: 'Experience Preferred to Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['Community building','Member engagement','Recruitment','Partnerships','Sponsorship outreach','Workshop planning','Public speaking','Professional communication'],
    what: "Grow Blueprint OTU's campus presence, member experience, recruitment pipeline, and external relationships.",
    roles: [
      {
        title: 'Community Director',
        experience: 'Experience Preferred',
        description: 'Builds the internal culture of Blueprint OTU and helps members feel connected, supported, and engaged.',
        responsibilities: [
          'Plan community-building initiatives for members',
          'Help onboard new members and make them feel welcomed',
          'Support member engagement, check-ins, and retention',
          'Create systems for feedback and communication',
          'Work with events and internal leadership to improve the member experience',
          'Help build a strong chapter culture from the ground up',
        ],
        requirements: [
          'Experience in clubs, student leadership, volunteering, mentorship, or community-building',
          'Strong communication and people skills',
          'Reliable, organized, and emotionally aware',
          'Comfortable checking in with members and helping solve small issues',
          'Able to create a welcoming and inclusive environment',
          'Good at noticing when people are disengaged or need support',
        ],
        niceToHave: [
          'Experience with onboarding, mentorship, or student engagement',
          'Notion, Google Forms, Discord, Slack, or community tools experience',
        ],
      },
      {
        title: 'Outreach / Recruitment Director',
        experience: 'Experience Preferred',
        description: 'Leads student recruitment and campus outreach to help Blueprint OTU grow its membership, visibility, mailing list, and application pipeline.',
        responsibilities: [
          'Plan recruitment campaigns for Fall/Winter/Summer',
          'Promote Blueprint OTU to students across programs',
          'Coordinate tabling, classroom visits, info sessions, and outreach messages',
          'Help grow the mailing list, Discord, and Instagram following',
          'Track recruitment interest and application numbers',
          'Work with Creative & Media to promote open roles',
        ],
        requirements: [
          'Experience with recruitment, outreach, clubs, ambassador work, or student engagement',
          'Comfortable talking to students and promoting opportunities',
          'Strong communication and organization skills',
          'Able to plan campaigns and follow up with interested students',
          'Confident representing Blueprint OTU professionally',
          'Comfortable working toward growth goals',
        ],
        niceToHave: [
          'Public speaking experience',
          'Experience with email campaigns, tabling, or orientation events',
          'Google Sheets/Forms or CRM-style tracking experience',
        ],
      },
      {
        title: 'Partnerships Director',
        experience: 'Experience Preferred to Experience Required',
        description: 'Builds relationships with nonprofits, student groups, campus departments, companies, and external organizations that can collaborate with Blueprint OTU.',
        responsibilities: [
          'Research potential nonprofit, campus, company, and community partners',
          'Send professional outreach emails',
          'Coordinate partnership conversations',
          'Help identify project opportunities for Blueprint teams',
          'Maintain a partner contact list',
          'Work with leadership to decide which partnerships align with the chapter',
        ],
        requirements: [
          'Strong written communication skills',
          'Comfortable sending professional emails and following up',
          'Experience with partnerships, sponsorships, outreach, student clubs, or community work',
          'Able to research organizations and understand their needs',
          'Professional, reliable, and organized',
          'Comfortable representing Blueprint OTU externally',
        ],
        niceToHave: [
          'Experience with nonprofit work or social impact projects',
          'LinkedIn networking experience',
          'Sponsorship or business development experience',
        ],
      },
      {
        title: 'Workshop Director',
        experience: 'Experience Preferred',
        description: 'Plans and coordinates skill-building workshops for students, members, and the wider Ontario Tech community.',
        responsibilities: [
          'Plan workshops around tech, design, GitHub, product, AI, social impact, and career skills',
          'Find speakers, facilitators, or student leads',
          'Coordinate workshop logistics, rooms, dates, and materials',
          'Work with Creative & Media to promote workshops',
          'Collect feedback after events',
          'Build a repeatable workshop series for the chapter',
        ],
        requirements: [
          'Experience planning workshops, events, tutorials, study sessions, or student programming',
          'Strong organization and communication skills',
          'Comfortable coordinating with speakers or facilitators',
          'Able to plan useful topics for students',
          'Reliable with deadlines and event logistics',
          'Comfortable hosting or supporting live sessions',
        ],
        niceToHave: [
          'Public speaking or teaching experience',
          'Experience with technical workshops, Figma workshops, GitHub workshops, or career panels',
        ],
      },
    ],
  },
  {
    id: 'development',
    name: 'Development Team',
    type: 'Technical',
    tagline: 'Build real software and digital products for nonprofits, community partners, and social impact projects.',
    experience: 'Experience Preferred to Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['React','Vue','TypeScript','JavaScript','Git / GitHub','APIs','Databases','Backend development','Figma','UI / UX','AI / ML','Mobile development','Project management'],
    what: 'Build real software and digital products for nonprofits, community partners, and social impact projects.',
    roles: [
      {
        title: 'Frontend Developer',
        experience: 'Experience Preferred',
        description: 'Builds user-facing web interfaces for Blueprint OTU projects, including nonprofit tools, internal platforms, and chapter website features.',
        responsibilities: [
          'Build responsive web pages and components',
          'Work with designers to turn Figma designs into functional interfaces',
          'Connect frontend pages to APIs when needed',
          'Fix UI bugs and improve usability',
          'Use Git/GitHub for collaboration',
          'Participate in code reviews, project meetings, and build sessions',
        ],
        requirements: [
          'Experience building websites or web apps',
          'Comfortable with HTML, CSS, JavaScript, and at least one frontend framework/library',
          'Experience with React, Vue, or similar tools',
          'Basic Git/GitHub knowledge',
          'Able to read designs and implement clean UI',
          'Willing to communicate progress and ask for help when blocked',
        ],
        niceToHave: [
          'TypeScript experience',
          'Tailwind CSS or component library experience',
          'Portfolio, GitHub projects, or deployed website',
        ],
      },
      {
        title: 'Backend Developer',
        experience: 'Experience Preferred to Experience Required',
        description: 'Builds the server-side logic, databases, APIs, and infrastructure needed for Blueprint OTU software projects.',
        responsibilities: [
          'Build and maintain backend APIs',
          'Design database models and data flows',
          'Implement authentication, validation, and server-side logic',
          'Connect backend services to frontend applications',
          'Write clean, maintainable code',
          'Use Git/GitHub for collaboration and code reviews',
        ],
        requirements: [
          'Experience with backend development through projects, coursework, internships, or personal work',
          'Comfortable with Node.js, Express, Python, Java, Spring Boot, or similar backend tools',
          'Basic understanding of REST APIs',
          'Basic database knowledge such as SQL, PostgreSQL, MySQL, MongoDB, or Firebase',
          'Able to debug and document backend work',
          'Comfortable collaborating with frontend developers',
        ],
        niceToHave: [
          'Authentication experience',
          'Docker or deployment experience',
          'Testing experience',
          'API documentation experience',
        ],
      },
      {
        title: 'UI/UX Designer',
        experience: 'Experience Preferred',
        description: 'Designs user-friendly digital products for Blueprint OTU projects, making sure tools are clear, accessible, and useful for real users.',
        responsibilities: [
          'Create wireframes, user flows, and high-fidelity designs',
          'Work with developers to hand off designs clearly',
          'Help conduct user research or usability feedback when needed',
          'Design interfaces for nonprofit and community-facing products',
          'Maintain consistency across product screens',
          'Support product thinking and user experience decisions',
        ],
        requirements: [
          'Experience with Figma or another design tool',
          'Understanding of UI layout, spacing, typography, and user flows',
          'Able to explain design decisions clearly',
          'Comfortable designing for real users, not just aesthetics',
          'Strong attention to detail',
          'Able to collaborate with developers and project managers',
        ],
        niceToHave: [
          'UX research experience',
          'Accessibility knowledge',
          'Design portfolio, Figma file, or case study',
        ],
      },
      {
        title: 'AI/ML Developer',
        experience: 'Experience Preferred to Experience Required',
        description: 'Supports projects that involve AI, automation, data processing, machine learning, or intelligent features for nonprofit/community use cases.',
        responsibilities: [
          'Build or prototype AI/ML features where appropriate',
          'Work with datasets, APIs, or model outputs',
          'Help evaluate whether AI is useful and ethical for a project',
          'Integrate AI tools into software products when needed',
          'Document models, prompts, workflows, or experiments',
          'Collaborate with developers, designers, and project leads',
        ],
        requirements: [
          'Experience with Python and basic machine learning, AI tools, or data projects',
          'Understanding of model inputs/outputs and limitations',
          'Comfortable experimenting, testing, and documenting results',
          'Able to explain technical ideas clearly to non-technical teammates',
          'Strong problem-solving skills',
          'Interest in responsible and useful AI for social good',
        ],
        niceToHave: [
          'Experience with scikit-learn, TensorFlow, PyTorch, OpenAI/Claude APIs, LangChain, or similar tools',
          'Data cleaning or analysis experience',
          'AI hackathon or personal project experience',
        ],
      },
      {
        title: 'Mobile Developer',
        experience: 'Experience Preferred',
        description: 'Builds mobile-first or mobile app experiences for Blueprint OTU projects when a nonprofit or community solution needs mobile access.',
        responsibilities: [
          'Build mobile app screens and features',
          'Work with designers to create usable mobile experiences',
          'Connect mobile apps to APIs or databases',
          'Test app flows on different screen sizes',
          'Collaborate with frontend/backend developers',
          'Document setup and development steps',
        ],
        requirements: [
          'Experience building mobile apps or mobile-first interfaces',
          'Comfortable with React Native, Flutter, Swift, Kotlin, or similar tools',
          'Basic understanding of app navigation, state, and API calls',
          'Able to use Git/GitHub',
          'Strong attention to mobile usability',
          'Comfortable learning and debugging mobile issues',
        ],
        niceToHave: [
          'Published app, GitHub repo, or prototype',
          'Firebase or Supabase experience',
          'UI/UX understanding for mobile apps',
        ],
      },
      {
        title: 'Product / Project Manager',
        experience: 'Experience Preferred to Experience Required',
        description: 'Keeps Blueprint OTU projects organized, scoped, and moving. This role connects developers, designers, stakeholders, and leadership.',
        responsibilities: [
          'Define project scope, goals, milestones, and deliverables',
          'Run or support weekly project check-ins',
          'Track tasks, deadlines, blockers, and team progress',
          'Communicate with nonprofit/community partners when needed',
          'Help translate user needs into product requirements',
          'Keep documentation organized',
          'Support final demos, project updates, and handoff materials',
        ],
        requirements: [
          'Experience leading projects, teams, events, clubs, hackathon teams, or technical work',
          'Strong organization and communication skills',
          'Able to break large goals into tasks and timelines',
          'Comfortable working with developers, designers, and stakeholders',
          'Good documentation habits',
          'Able to keep a team accountable without micromanaging',
        ],
        niceToHave: [
          'Agile, Scrum, Kanban, Notion, Jira, Trello, or GitHub Projects experience',
          'Product management or business analysis experience',
          'Experience working with clients, nonprofits, or external partners',
        ],
      },
    ],
  },
  {
    id: 'executive',
    name: 'Executive Team',
    type: 'Leadership',
    tagline: 'Lead the systems, strategy, operations, partnerships, projects, marketing, and execution behind Blueprint OTU.',
    experience: 'Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['Leadership','Team management','Operations','Communication','Sponsorships','Event planning','Project oversight','Marketing strategy','Website management','Documentation'],
    what: 'Lead the systems, strategy, operations, partnerships, projects, marketing, and execution behind Blueprint OTU.',
    roles: [
      {
        title: 'VP Internal',
        experience: 'Experience Required',
        description: 'Leads internal operations, member experience, onboarding, documentation, and chapter systems.',
        responsibilities: [
          'Manage internal communication systems and documentation',
          'Support onboarding for new members',
          'Help organize meetings, internal updates, and team workflows',
          'Track member engagement and internal needs',
          'Support conflict resolution and team coordination',
          'Maintain internal resources, templates, and processes',
        ],
        requirements: [
          'Previous leadership, club, operations, or team coordination experience',
          'Strong organization and communication skills',
          'Reliable with follow-ups, documentation, and deadlines',
          'Comfortable managing internal systems such as Notion, Google Drive, Discord, or Slack',
          'Able to support members professionally and respectfully',
          'Strong attention to detail',
        ],
        niceToHave: [
          'Experience with onboarding, HR-style processes, or member management',
          'Experience building systems from scratch',
          'Notion/database experience',
        ],
      },
      {
        title: 'VP External',
        experience: 'Experience Required',
        description: 'Leads external relationships, sponsorships, partnerships, nonprofit outreach, and professional communication for Blueprint OTU.',
        responsibilities: [
          'Build relationships with companies, nonprofits, campus partners, and community organizations',
          'Oversee sponsorship and partnership outreach',
          'Support partnership proposals and external communications',
          'Maintain external contact lists and follow-up systems',
          'Represent Blueprint OTU professionally in meetings and emails',
          'Work with the President and leadership team on growth strategy',
        ],
        requirements: [
          'Experience with outreach, sponsorships, partnerships, business development, clubs, or external relations',
          'Strong professional writing and communication skills',
          'Comfortable sending emails and following up consistently',
          'Able to speak confidently with external partners',
          'Organized and reliable with relationship tracking',
          "Strong understanding of Blueprint OTU's mission and brand",
        ],
        niceToHave: [
          'Sponsorship package or pitch deck experience',
          'LinkedIn networking experience',
          'Experience working with nonprofits, startups, or campus departments',
        ],
      },
      {
        title: 'VP Events',
        experience: 'Experience Required',
        description: 'Leads the planning and execution of Blueprint OTU events, including workshops, info sessions, panels, socials, build nights, and flagship events.',
        responsibilities: [
          'Plan the semester event calendar',
          'Oversee event coordinators and workshop/event leads',
          'Manage event logistics, rooms, timelines, materials, and volunteers',
          'Work with Creative & Media on event promotion',
          'Coordinate with speakers, partners, and campus groups',
          'Collect feedback and improve future events',
        ],
        requirements: [
          'Experience planning events, workshops, panels, socials, hackathons, or student programming',
          'Strong logistics and communication skills',
          'Able to manage timelines and multiple moving pieces',
          'Comfortable leading volunteers or event teams',
          'Reliable under deadlines and event pressure',
          'Able to create events that feel organized and valuable',
        ],
        niceToHave: [
          'Experience with room bookings, speaker coordination, or large student events',
          'Public speaking or hosting experience',
          'Event budgeting experience',
        ],
      },
      {
        title: 'VP Projects',
        experience: 'Experience Required',
        description: "Oversees Blueprint OTU's project pipeline, project teams, nonprofit/client work, and final deliverables.",
        responsibilities: [
          'Help select and scope projects for the chapter',
          'Support project managers, developers, and designers',
          'Track project progress, blockers, and deliverables',
          'Help coordinate client/nonprofit communication',
          'Ensure teams are building useful, realistic, and well-scoped products',
          'Support project demos, documentation, and handoff',
        ],
        requirements: [
          'Experience leading technical, design, product, hackathon, or club projects',
          'Strong understanding of software/project workflows',
          'Able to communicate with both technical and non-technical people',
          'Strong organization and problem-solving skills',
          'Comfortable giving feedback and keeping teams accountable',
          'Able to balance ambition with realistic scope',
        ],
        niceToHave: [
          'Product/project management experience',
          'GitHub Projects, Notion, Jira, Trello, or Agile experience',
          'Experience working with clients, nonprofits, or stakeholders',
        ],
      },
      {
        title: 'VP Marketing / Creative',
        experience: 'Experience Required',
        description: "Leads Blueprint OTU's marketing strategy, visual brand, campaigns, content direction, and public-facing storytelling.",
        responsibilities: [
          'Own the marketing and creative direction for the chapter',
          'Oversee social media, design, content, and campaign planning',
          'Lead recruitment campaigns and event promotion strategy',
          'Ensure all public-facing materials feel consistent and polished',
          'Work with the Social Media Director, Director of Design, and content team',
          'Track marketing performance and improve growth strategy',
        ],
        requirements: [
          'Experience with marketing, branding, social media, design direction, content strategy, or campaign planning',
          'Strong understanding of visual consistency and audience engagement',
          'Able to lead creative people and give useful feedback',
          'Strong writing and communication skills',
          'Organized enough to manage campaigns and deadlines',
          'Able to make Blueprint OTU look credible, active, and professional',
        ],
        niceToHave: [
          'Experience growing a social media page or brand',
          'Figma, Canva, Adobe, CapCut, or analytics experience',
          'Portfolio, campaign examples, or design/content samples',
        ],
      },
      {
        title: 'VP Tech / Web',
        experience: 'Experience Required',
        description: "Leads Blueprint OTU's technical infrastructure, website, digital tools, and internal tech systems.",
        responsibilities: [
          'Maintain and improve the Blueprint OTU website',
          'Oversee technical tools, forms, integrations, and digital systems',
          'Support the Development Team with technical direction when needed',
          'Help review technical feasibility for projects and website features',
          'Manage GitHub or deployment workflows where applicable',
          'Ensure digital platforms are reliable, organized, and easy to use',
        ],
        requirements: [
          'Strong web development or technical project experience',
          'Comfortable with frontend development and basic backend/integration concepts',
          'Experience with Git/GitHub',
          'Able to debug issues and improve digital workflows',
          'Strong documentation and communication skills',
          'Able to make technical decisions responsibly',
        ],
        niceToHave: [
          'React, Vue, TypeScript, Node.js, or deployment experience',
          'Experience with forms, databases, APIs, or automation tools',
          'Previous website management experience',
        ],
      },
    ],
  },
]

export const ROLE_MAP: Record<string, string[]> = {
  creative:    ['Social Media Director','Content Creator','Photographer / Videographer','Director of Design'],
  community:   ['Community Director','Outreach / Recruitment Director','Partnerships Director','Workshop Director'],
  development: ['Frontend Developer','Backend Developer','UI/UX Designer','AI/ML Developer','Mobile Developer','Product / Project Manager'],
  executive:   ['VP Internal','VP External','VP Events','VP Projects','VP Marketing / Creative','VP Tech / Web'],
}

export const PROCESS_STEPS = [
  { n:'01', title:'Explore teams',       desc:'Browse our four teams and find the one that matches your skills and interests.' },
  { n:'02', title:'Choose your role',    desc:'Click into a team to see all open roles with full qualifications.' },
  { n:'03', title:'Submit application',  desc:'Fill out the form honestly. It takes about 15 minutes.' },
  { n:'04', title:'Interview or review', desc:'Some roles include a short conversation, portfolio review, or role-specific follow-up.' },
  { n:'05', title:'Join the cohort',     desc:'Selected applicants are onboarded before the semester begins.' },
]

export const FAQ = [
  { q:'Do I need experience?',                   a:'It depends on the role. Creative and community roles are beginner-friendly. Technical and executive roles require demonstrated ability. But across every role, we care more about your drive and honesty than your resume.' },
  { q:'Do I need to meet every qualification?',  a:'No. Qualifications are guidelines, not gates. If you have some of the listed skills and genuine motivation to learn the rest, we want to hear from you. Apply and tell us your story.' },
  { q:'How much time is required?',              a:'All selected members commit approximately 8 hours per week minimum. Some roles, especially executive and project-facing ones, may require more during busy periods.' },
  { q:'Can first-years apply?',                  a:'Yes. First-years are welcome if you are reliable, motivated, and ready to contribute consistently from day one.' },
  { q:'Can non-engineering students apply?',     a:'Absolutely. Blueprint needs designers, communicators, event planners, storytellers, and strategists just as much as developers. Your program is not a barrier.' },
  { q:'Can I apply to more than one role?',      a:'Yes. Select your strongest fit as your primary role, then choose a secondary team or role if you are genuinely open to being considered elsewhere.' },
  { q:'What happens after I apply?',             a:'Applications are reviewed by the leadership team. Some applicants will be invited for a short conversation. You will hear back via your OTU email within 7 days.' },
  { q:'Is this paid?',                           a:'No. Blueprint OTU is a volunteer student organization. We are here for the experience, the community, and the impact.' },
  { q:"What if I don't have an OTU email yet?",  a:"If you are an incoming student who does not have your OTU email yet, apply with your personal email and note that in your application." },
]

export const TICKER = [
  'Technology for Good','Ontario Tech University','Durham Region',
  'Pro Bono Software','Student Developers','Community Impact',
  'Hack for Impact','Applications Open Now',
  'Zero Cost to Nonprofits','First Cohort Fall 2026',
]