import type { BpEvent, Member } from './types'

export const EVENTS: BpEvent[] = [
  { id:1, title:'Hack for Impact',            date:'November 1st, 2026', time:'TBD', loc:'TBD', type:'flagship', desc:'Our first annual hackathon. Student teams build real tech solutions for Durham Region nonprofits. Open to every program at OTU.', cap:100, status:'upcoming'    },
  { id:2, title:'Tech for Good Panel',        date:'Nov 2026',           time:'TBD', loc:'TBD', type:'panel',    desc:'90 minutes with OTU professors, Durham nonprofit leaders, and people working in social impact tech. Open to the whole campus.', cap:80,  status:'placeholder' },
  { id:3, title:'Learn Lab Series',           date:'Oct 2026',           time:'TBD', loc:'TBD', type:'lab',      desc:'Monthly skill sessions covering React, Figma, Git, agile, and client communication. Hands-on and beginner friendly.',           cap:40,  status:'placeholder' },
  { id:4, title:'Fall Info Session',          date:'Sept 2026',          time:'TBD', loc:'TBD', type:'social',   desc:'Learn what Blueprint is, meet the team, and find out how to apply. Food provided. Come as you are.',                           cap:60,  status:'upcoming'    },
  { id:5, title:'NPO Showcase Night',         date:'Apr 2027',           time:'TBD', loc:'TBD', type:'flagship', desc:'End of year demo night. Each team presents their delivered software to nonprofit clients, sponsors, faculty, and campus.',     cap:120, status:'placeholder' },
  { id:6, title:'Coffee Chats with Industry', date:'Monthly',            time:'TBD', loc:'TBD', type:'social',   desc:'Monthly 60-minute session with one industry professional. 15 Blueprint members. No slides, just real talk.',                   cap:15,  status:'placeholder' },
]

export const TEAM: Member[] = [
  { id:1, name:'Jun Bin Cheng',     role:'Founder',                        program:'Ontario Tech University', year:'', initials:'J', isExec:true },
  { id:2, name:'Valerie Ekeigwe',   role:'President',                      program:'Ontario Tech University', year:'', initials:'V', isExec:true },
  { id:3, name:'Kumayl Zafar',      role:'Vice President',                 program:'Ontario Tech University', year:'', initials:'K', isExec:true },
  { id:4, name:'Ngozika Nwachukwu', role:'VP of Technological Operations', program:'Ontario Tech University', year:'', initials:'N', isExec:true },
]

export const TEAMS = [
  {
    id: 'creative',
    name: 'Creative & Media Team',
    type: 'Creative',
    tagline: "Shape Blueprint OTU's brand, content, and storytelling across social media, events, recruitment, and digital platforms.",
    experience: 'Beginner-Friendly to Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['Social media strategy','Instagram','LinkedIn','Content planning','Canva','Figma','Photography','Video editing','Branding','Copywriting'],
    what: "Shape Blueprint OTU's brand, content, and storytelling across social media, events, recruitment, and digital platforms.",
    roles: [
      {
        title: 'Social Media Manager',
        experience: 'Experience Preferred',
        description: "Leads Blueprint OTU's online presence across Instagram, LinkedIn, and other platforms. This role owns the content calendar, campaign direction, posting schedule, and overall social media voice.",
        responsibilities: [
          'Plan and manage the weekly/monthly content calendar',
          'Lead Instagram and LinkedIn content strategy',
          'Coordinate recruitment campaigns, event promotions, and announcements',
          'Write or review captions, post copy, and story content',
          'Track engagement, follower growth, and campaign performance',
          'Work with photographers and content creators to produce posts',
          "Make sure Blueprint OTU's online presence feels consistent and professional",
        ],
        requirements: [
          'Experience managing or helping run a social media page, club page, brand page, or personal content account',
          'Strong understanding of Instagram content, captions, stories, reels, and post timing',
          'Good writing and communication skills',
          'Organized enough to manage deadlines and posting schedules',
          'Able to understand the Blueprint OTU brand and keep content consistent',
          'Comfortable giving direction to content creators',
        ],
        niceToHave: [
          'Canva, Figma, CapCut, or Adobe experience',
          'Experience with analytics/insights',
          'Experience growing a page or running campaigns',
        ],
      },
      {
        title: 'Content Creator',
        experience: 'Beginner-Friendly to Experience Preferred',
        description: 'Creates short-form content, captions, reels, stories, and behind-the-scenes content that makes Blueprint OTU feel active, human, and engaging.',
        responsibilities: [
          'Create Instagram reels, stories, and short-form videos',
          'Capture behind-the-scenes moments at meetings and events',
          'Help write captions and content ideas',
          'Support recruitment campaigns and event promotions',
          'Turn club updates into engaging student-friendly content',
          'Work with the Social Media Manager to follow the content calendar',
        ],
        requirements: [
          'Experience creating content for Instagram, TikTok, YouTube Shorts, clubs, events, or personal projects',
          'Comfortable filming, editing, or planning content',
          'Good sense of what feels engaging to students',
          'Able to follow brand direction and deadlines',
          'Strong communication and creativity',
          'Comfortable being at events or working with people to capture content',
        ],
        niceToHave: [
          'CapCut, Canva, Adobe, or phone video editing experience',
          'Basic photography/videography skills',
          'Experience writing captions or hooks',
        ],
      },
      {
        title: 'Photographer / Videographer',
        experience: 'Experience Preferred',
        description: 'Captures high-quality photos and videos for Blueprint OTU events, campaigns, recruitment, and brand storytelling.',
        responsibilities: [
          'Take photos and videos at events, workshops, meetings, and campaigns',
          'Capture clean, professional-looking content for Instagram and LinkedIn',
          'Edit photos/videos when needed',
          'Organize media files for the team',
          'Work with the Creative & Media team to plan shoots',
          'Help create visual content that makes the chapter look active and credible',
        ],
        requirements: [
          'Experience taking photos or videos for events, clubs, personal projects, or clients',
          'Comfortable using a camera or phone camera well',
          'Basic understanding of lighting, framing, and composition',
          'Able to deliver content on time after events',
          'Organized with file storage and sharing',
          'Comfortable attending events to capture content',
        ],
        niceToHave: [
          'DSLR/mirrorless camera access',
          'Lightroom, Photoshop, Premiere Pro, CapCut, or DaVinci Resolve experience',
          'Experience shooting event recaps or social media reels',
        ],
      },
    ],
  },
  {
    id: 'community',
    name: 'Community & Outreach Team',
    type: 'Outreach',
    tagline: "Grow Blueprint OTU's funding, sponsorships, and external relationships while supporting the chapter's financial health.",
    experience: 'Beginner-Friendly to Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['Sponsorship outreach','Fundraising','Financial tracking','Professional communication','Partnership building','Grant writing','Budget management','Community engagement'],
    what: "Grow Blueprint OTU's funding, sponsorships, and external relationships while supporting the chapter's financial health.",
    roles: [
      {
        title: 'Sponsorship Associate',
        experience: 'Experience Preferred to Experience Required',
        description: 'Leads high-level sponsorship and partnership outreach for Blueprint OTU. This role builds relationships with companies, organizations, and campus partners to secure funding, resources, and opportunities that support the chapter at scale.',
        responsibilities: [
          'Research and identify potential sponsors, corporate partners, and funding sources',
          'Draft and send professional sponsorship proposals and outreach emails',
          'Manage sponsor relationships and follow-up communications',
          'Negotiate sponsorship agreements and deliverables',
          'Maintain a sponsor contact list and partnership tracker',
          'Work with leadership to align sponsorships with chapter goals',
          'Represent Blueprint OTU professionally in external meetings',
        ],
        requirements: [
          'Experience with outreach, partnerships, sponsorships, or business development',
          'Strong professional writing and communication skills',
          'Comfortable sending cold emails and following up consistently',
          'Able to research organizations and understand their sponsorship interests',
          'Organized and reliable with relationship management',
          'Confident representing Blueprint OTU externally',
        ],
        niceToHave: [
          'Sponsorship package or pitch deck experience',
          'LinkedIn networking experience',
          'Experience working with nonprofits, startups, or campus departments',
          'Knowledge of sponsorship tiers and benefits structures',
        ],
      },
      {
        title: 'Fundraising Coordinator',
        experience: 'Beginner-Friendly to Experience Preferred',
        description: "Supports Blueprint OTU's financial health by coordinating fundraising efforts, tracking income and expenses, managing receipts, and pursuing smaller-scale funding opportunities. This role is part finance officer and part fundraiser — keeping the books organized while actively helping bring money in.",
        responsibilities: [
          'Track chapter income, expenses, and receipts in an organized system',
          'Research and apply for student union funding, grants, and micro-sponsorships',
          'Coordinate fundraising initiatives and campaigns',
          'Message potential small-scale donors, local businesses, and community partners',
          'Maintain accurate financial records for chapter transparency',
          'Support the Sponsorship Associate with administrative and outreach tasks',
          'Help prepare financial summaries for leadership when needed',
        ],
        requirements: [
          'Organized, detail-oriented, and reliable with numbers and records',
          'Comfortable managing spreadsheets, receipts, and financial tracking',
          'Willing to send outreach messages and follow up with potential donors',
          'Good written communication skills',
          'Trustworthy and responsible with financial information',
          'Interest in fundraising, finance, or nonprofit operations',
        ],
        niceToHave: [
          'Experience with bookkeeping, budgeting, or finance coursework',
          'Experience applying for grants or student funding',
          'Google Sheets or Excel experience',
          'Previous club treasurer or finance experience',
        ],
      },
    ],
  },
  {
    id: 'development',
    name: 'Development Team',
    type: 'Technical',
    tagline: 'Build real software and digital products for nonprofits, community partners, and social impact projects.',
    experience: 'Experience Preferred to Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['React','Vue','TypeScript','JavaScript','Git / GitHub','APIs','Databases','Backend development','Figma','UI / UX','AI / ML','Mobile development','Project management'],
    what: 'Build real software and digital products for nonprofits, community partners, and social impact projects.',
    roles: [
      {
        title: 'Frontend Developer',
        experience: 'Experience Preferred',
        description: 'Builds user-facing web interfaces for Blueprint OTU projects, including nonprofit tools, internal platforms, and chapter website features.',
        responsibilities: [
          'Build responsive web pages and components',
          'Work with designers to turn Figma designs into functional interfaces',
          'Connect frontend pages to APIs when needed',
          'Fix UI bugs and improve usability',
          'Use Git/GitHub for collaboration',
          'Participate in code reviews, project meetings, and build sessions',
        ],
        requirements: [
          'Experience building websites or web apps',
          'Comfortable with HTML, CSS, JavaScript, and at least one frontend framework/library',
          'Experience with React, Vue, or similar tools',
          'Basic Git/GitHub knowledge',
          'Able to read designs and implement clean UI',
          'Willing to communicate progress and ask for help when blocked',
        ],
        niceToHave: [
          'TypeScript experience',
          'Tailwind CSS or component library experience',
          'Portfolio, GitHub projects, or deployed website',
        ],
      },
      {
        title: 'Backend Developer',
        experience: 'Experience Preferred to Experience Required',
        description: 'Builds the server-side logic, databases, APIs, and infrastructure needed for Blueprint OTU software projects.',
        responsibilities: [
          'Build and maintain backend APIs',
          'Design database models and data flows',
          'Implement authentication, validation, and server-side logic',
          'Connect backend services to frontend applications',
          'Write clean, maintainable code',
          'Use Git/GitHub for collaboration and code reviews',
        ],
        requirements: [
          'Experience with backend development through projects, coursework, internships, or personal work',
          'Comfortable with Node.js, Express, Python, Java, Spring Boot, or similar backend tools',
          'Basic understanding of REST APIs',
          'Basic database knowledge such as SQL, PostgreSQL, MySQL, MongoDB, or Firebase',
          'Able to debug and document backend work',
          'Comfortable collaborating with frontend developers',
        ],
        niceToHave: [
          'Authentication experience',
          'Docker or deployment experience',
          'Testing experience',
          'API documentation experience',
        ],
      },
      {
        title: 'UI/UX Designer',
        experience: 'Experience Preferred',
        description: 'Designs user-friendly digital products for Blueprint OTU projects, making sure tools are clear, accessible, and useful for real users.',
        responsibilities: [
          'Create wireframes, user flows, and high-fidelity designs',
          'Work with developers to hand off designs clearly',
          'Help conduct user research or usability feedback when needed',
          'Design interfaces for nonprofit and community-facing products',
          'Maintain consistency across product screens',
          'Support product thinking and user experience decisions',
        ],
        requirements: [
          'Experience with Figma or another design tool',
          'Understanding of UI layout, spacing, typography, and user flows',
          'Able to explain design decisions clearly',
          'Comfortable designing for real users, not just aesthetics',
          'Strong attention to detail',
          'Able to collaborate with developers and project managers',
        ],
        niceToHave: [
          'UX research experience',
          'Accessibility knowledge',
          'Design portfolio, Figma file, or case study',
        ],
      },
      {
        title: 'AI/ML Developer',
        experience: 'Experience Preferred to Experience Required',
        description: 'Supports projects that involve AI, automation, data processing, machine learning, or intelligent features for nonprofit/community use cases.',
        responsibilities: [
          'Build or prototype AI/ML features where appropriate',
          'Work with datasets, APIs, or model outputs',
          'Help evaluate whether AI is useful and ethical for a project',
          'Integrate AI tools into software products when needed',
          'Document models, prompts, workflows, or experiments',
          'Collaborate with developers, designers, and project leads',
        ],
        requirements: [
          'Experience with Python and basic machine learning, AI tools, or data projects',
          'Understanding of model inputs/outputs and limitations',
          'Comfortable experimenting, testing, and documenting results',
          'Able to explain technical ideas clearly to non-technical teammates',
          'Strong problem-solving skills',
          'Interest in responsible and useful AI for social good',
        ],
        niceToHave: [
          'Experience with scikit-learn, TensorFlow, PyTorch, OpenAI/Claude APIs, LangChain, or similar tools',
          'Data cleaning or analysis experience',
          'AI hackathon or personal project experience',
        ],
      },
      {
        title: 'Mobile Developer',
        experience: 'Experience Preferred',
        description: 'Builds mobile-first or mobile app experiences for Blueprint OTU projects when a nonprofit or community solution needs mobile access.',
        responsibilities: [
          'Build mobile app screens and features',
          'Work with designers to create usable mobile experiences',
          'Connect mobile apps to APIs or databases',
          'Test app flows on different screen sizes',
          'Collaborate with frontend/backend developers',
          'Document setup and development steps',
        ],
        requirements: [
          'Experience building mobile apps or mobile-first interfaces',
          'Comfortable with React Native, Flutter, Swift, Kotlin, or similar tools',
          'Basic understanding of app navigation, state, and API calls',
          'Able to use Git/GitHub',
          'Strong attention to mobile usability',
          'Comfortable learning and debugging mobile issues',
        ],
        niceToHave: [
          'Published app, GitHub repo, or prototype',
          'Firebase or Supabase experience',
          'UI/UX understanding for mobile apps',
        ],
      },
      {
        title: 'Product / Project Manager',
        experience: 'Experience Preferred to Experience Required',
        description: 'Keeps Blueprint OTU projects organized, scoped, and moving. This role connects developers, designers, stakeholders, and leadership.',
        responsibilities: [
          'Define project scope, goals, milestones, and deliverables',
          'Run or support weekly project check-ins',
          'Track tasks, deadlines, blockers, and team progress',
          'Communicate with nonprofit/community partners when needed',
          'Help translate user needs into product requirements',
          'Keep documentation organized',
          'Support final demos, project updates, and handoff materials',
        ],
        requirements: [
          'Experience leading projects, teams, events, clubs, hackathon teams, or technical work',
          'Strong organization and communication skills',
          'Able to break large goals into tasks and timelines',
          'Comfortable working with developers, designers, and stakeholders',
          'Good documentation habits',
          'Able to keep a team accountable without micromanaging',
        ],
        niceToHave: [
          'Agile, Scrum, Kanban, Notion, Jira, Trello, or GitHub Projects experience',
          'Product management or business analysis experience',
          'Experience working with clients, nonprofits, or external partners',
        ],
      },
    ],
  },
  {
    id: 'executive',
    name: 'Executive Team',
    type: 'Leadership',
    tagline: 'Lead the systems, strategy, operations, events, and execution behind Blueprint OTU.',
    experience: 'Experience Required',
    status: 'Open Now',
    commitment: '8 hrs/week minimum',
    skills: ['Leadership','Team management','Operations','Communication','Event planning','Technical oversight','Documentation','Strategic planning'],
    what: 'Lead the systems, strategy, operations, events, and execution behind Blueprint OTU.',
    roles: [
      {
        title: 'VP Events',
        experience: 'Experience Required',
        description: 'Leads the planning and execution of Blueprint OTU events, including workshops, info sessions, panels, socials, build nights, and flagship events.',
        responsibilities: [
          'Plan the semester event calendar',
          'Oversee event coordinators and workshop/event leads',
          'Manage event logistics, rooms, timelines, materials, and volunteers',
          'Work with Creative & Media on event promotion',
          'Coordinate with speakers, partners, and campus groups',
          'Collect feedback and improve future events',
        ],
        requirements: [
          'Experience planning events, workshops, panels, socials, hackathons, or student programming',
          'Strong logistics and communication skills',
          'Able to manage timelines and multiple moving pieces',
          'Comfortable leading volunteers or event teams',
          'Reliable under deadlines and event pressure',
          'Able to create events that feel organized and valuable',
        ],
        niceToHave: [
          'Experience with room bookings, speaker coordination, or large student events',
          'Public speaking or hosting experience',
          'Event budgeting experience',
        ],
      },
      {
        title: 'VP of Internal Operations',
        experience: 'Experience Required',
        description: 'Leads internal operations, member experience, onboarding, documentation, and chapter systems. This role keeps Blueprint OTU running smoothly behind the scenes.',
        responsibilities: [
          'Manage internal communication systems and documentation',
          'Support onboarding for new members',
          'Help organize meetings, internal updates, and team workflows',
          'Track member engagement and internal needs',
          'Support conflict resolution and team coordination',
          'Maintain internal resources, templates, and processes',
          'Ensure the chapter runs efficiently and members feel supported',
        ],
        requirements: [
          'Previous leadership, club, operations, or team coordination experience',
          'Strong organization and communication skills',
          'Reliable with follow-ups, documentation, and deadlines',
          'Comfortable managing internal systems such as Notion, Google Drive, Discord, or Slack',
          'Able to support members professionally and respectfully',
          'Strong attention to detail',
        ],
        niceToHave: [
          'Experience with onboarding, HR-style processes, or member management',
          'Experience building systems from scratch',
          'Notion or database experience',
        ],
      },
    ],
  },
]

export const ROLE_MAP: Record<string, string[]> = {
  creative:    ['Social Media Manager','Content Creator','Photographer / Videographer'],
  community:   ['Sponsorship Associate','Fundraising Coordinator'],
  development: ['Frontend Developer','Backend Developer','UI/UX Designer','AI/ML Developer','Mobile Developer','Product / Project Manager'],
  executive:   ['VP Events','VP of Internal Operations'],
}

export const PROCESS_STEPS = [
  { n:'01', title:'Explore teams',       desc:'Browse our four teams and find the one that matches your skills and interests.' },
  { n:'02', title:'Choose your role',    desc:'Click into a team to see all open roles with full qualifications.' },
  { n:'03', title:'Submit application',  desc:'Fill out the form honestly. It takes about 15 minutes.' },
  { n:'04', title:'Interview or review', desc:'Some roles include a short conversation, portfolio review, or role-specific follow-up.' },
  { n:'05', title:'Join the cohort',     desc:'Selected applicants are onboarded before the semester begins.' },
]

export const FAQ = [
  { q:'Do I need experience?',                   a:'It depends on the role. Creative and community roles are beginner-friendly. Technical and executive roles require demonstrated ability. But across every role, we care more about your drive and honesty than your resume.' },
  { q:'Do I need to meet every qualification?',  a:'No. Qualifications are guidelines, not gates. If you have some of the listed skills and genuine motivation to learn the rest, we want to hear from you. Apply and tell us your story.' },
  { q:'How much time is required?',              a:'All selected members commit approximately 8 hours per week minimum. Some roles, especially executive and project-facing ones, may require more during busy periods.' },
  { q:'Can first-years apply?',                  a:'Yes. First-years are welcome if you are reliable, motivated, and ready to contribute consistently from day one.' },
  { q:'Can non-engineering students apply?',     a:'Absolutely. Blueprint needs designers, communicators, event planners, storytellers, and strategists just as much as developers. Your program is not a barrier.' },
  { q:'Can I apply to more than one role?',      a:'Yes. Select your strongest fit as your primary role, then choose a secondary team or role if you are genuinely open to being considered elsewhere.' },
  { q:'What happens after I apply?',             a:'Applications are reviewed by the leadership team. Some applicants will be invited for a short conversation. You will hear back via your OTU email within 7 days.' },
  { q:'Is this paid?',                           a:'No. Blueprint OTU is a volunteer student organization. We are here for the experience, the community, and the impact.' },
  { q:"What if I don't have an OTU email yet?",  a:"If you are an incoming student who does not have your OTU email yet, apply with your personal email and note that in your application." },
]

export const TICKER = [
  'Technology for Good','Ontario Tech University','Durham Region',
  'Pro Bono Software','Student Developers','Community Impact',
  'Hack for Impact','Applications Open Now',
  'Zero Cost to Nonprofits','First Cohort Fall 2026',
]